name: Deploy the application
on:
   workflow_dispatch:
   push:
      branches:
         - dev
         - main
jobs:
   check_deploy_target:
      runs-on: ubuntu-latest
      steps:
         - run: echo "Deploying the application to ${{ inputs.deploy_target }}"
   deploy:
      runs-on: ubuntu-latest
      needs:
         - check_deploy_target
      steps:
         - run: echo "${{ inputs.deploy_target }}"
